### PR TITLE
Support offline usage with docker

### PR DESCRIPTION
**Pull request by harmangakhal**
After running the configuration script and starting go-dappley,

```
docker-compose build # requires internet to pull images
docker-compose up
```
The same instructions apply to starting `go-dappley`.

### CODE REVIEW

**Comment by rwwong** [comment]
@harmangakhal Would you mind describing more about the scenarios where normal usage or offline usage apply?

**Comment by harmangakhal** [comment]
@rwwong 
The `NODE_IP` requires that the node have an private/public IP address; it helps with debugging as you can run `./dapp` locally instead of in a container and use your IP.

The default option simplifies the deploy and can run on a host without internet using 3 docker containers after packaging/loading the images.

**Comment by rwwong** [comment]
With offline usage, if docker container for `dappley` is not running, `grpc-proxy` cannot start. Is it possible to still have it running regardless of the running status of dappley?

**Comment by harmangakhal** [comment]
> With offline usage, if docker container for `dappley` is not running, `grpc-proxy` cannot start. Is it possible to still have it running regardless of the running status of dappley?

Yes, removing these lines will accomplish that, https://github.com/dappley/dappley-stats/blob/4b6fc4a33b9c124f700d661fb3ac3b50e0c21c80/cm/templates/docker-compose.yml.mustache#L23-L26.

**Comment by harmangakhal** [comment]
> https://github.com/dappley/dappley-stats/blob/offline-docker/cm/templates/config.json.mustache#L2
> Should grpc host always be 0.0.0.0? I find myself changing it in order to avoid CORS.

Hmm, that's strange, I've never had to change it but maybe this configuration needs to be tweaked? https://github.com/dappley/dappley-stats/blob/49721845bd307d93c26ba3fa2f1c0c6cc1cb756c/cm/templates/docker/grpc-proxy/envoy.yaml.mustache#L21-L27

**Pull request merged**
